services:
  gexdex-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-gexdex-api-container}
    ports:
      - "${PORT:-8090}:8000"
    environment:
      - API_KEY=${API_KEY:-YOUR_SECRET_API_KEY_HERE}
    volumes:
      - ${COMMON_LIB_PATH:-/volume2/homes/rachardv/git-repos/master/common-lib/common_lib}:/app/common_lib
      - ${COMMON_CONFIG_PATH:-/volume2/homes/rachardv/git-repos/master/common_config}:/app/common_config
    restart: always
