version: '3.8'

services:
  gexdex-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gexdex-api-container
    ports:
      - "8090:8000"
    environment:
      - API_KEY=YOUR_SECRET_API_KEY_HERE
    volumes:
      - /volume2/homes/rachardv/git-repos/master/common-lib/common_lib:/app/common_lib
      - /volume2/homes/rachardv/git-repos/master/common_config:/app/common_config
    restart: always

